---
# tasks file for securitygroup
      - name: example ec2 group
        ec2_group:
           name: launch-wizard-4
           description: ec2 security group
           region: us-east-1
           vpc_id: vpc-6ac60d0c
           rules:
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 443
              to_port: 443
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0

